terraform-aws-modules/terraform-aws-atlantis

- README.md
- main.tf
- variables.tf
This PR solves #7 by introducing a policies_arn input variable (list, defaults to ["arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"]).
> #7 pass ECs task exec. policy as input variable

- main.tf
- variables.tf
Allow the gitlab hostname to be configured using the `ATLANTIS_GITLAB_HOSTNAME` environment variable.
> Add variable to configure gitlab hostname

- main.tf
Solves #24.
Creates a new security group to allow http ingress to the ALB and a new lb listener rule to redirect traffic from port 80 HTTP to 443 HTTPS.
> Add http -> https redirect on the ALB

- README.md
- main.tf
- variables.tf
This is a follow-up for #35 and #36
It was faster for me to merge these two together and run tests once.
Thanks @stephencoe and @chenrui333 !
> Added container_memory_reservation config and extended container_definitions

- outputs.tf
I would like to add VPC ID to the outputs of the Atlantis terraform module.
Currently, when you spin up a VPC, AWS by default attaches a security group that has permissions that are broader than desirable. In order to remove this security group and replace it with one more appropriate, we'd like to have the VPC ID available to apply more changes after its creation.
> add vpc_id to outputs

- README.md
As an example /20 won't work as it covers until "10.20.15.255" (4096 possible IPs).
> replace /20 to /16 in README.md

- main.tf
We are using a pre-created cert and passing in an ACM cert arn (`certificate_arn`), using a domain name that's not Route53 (`create_route53_record = false`), and the acm cert module invocation errors with:
```
Error: Error running plan: 1 error(s) occurred:
* module.atlantis.module.acm.var.zone_id: Resource 'data.aws_route53_zone.this' not found for variable 'data.aws_route53_zone.this.id'
```
This is a workaround for terraform to not error when invoking the ACM cert module when not using route53, and not creating an ACM cert..
> Workaround to not error on accessing value on a data element that does not exist

- outputs.tf
For our use case, we are using the ALB DNS name to create an external DNS record to the atlantis load balancer. This adds the ALB DNS name to the outputs.
> Output alb dns name

- README.md
- main.tf
- outputs.tf
- terraform.tfvars.sample
- variables.tf
Based on #43 by @trebidav
An important addition is that this module requires one group of secrets to be set - github, gitlab or bitbucket.
> Add support for Bitbucket Cloud

- main.tf
Fixed to follow atlantis master using `ATLANTIS_GH_TOKEN` not `ATLANTIS_GITHUB_TOKEN`
https://github.com/runatlantis/atlantis/blob/master/cmd/server.go#L137
> Fix github user token env to ATLANTIS_GH_TOKEN

- README.md
- main.tf
- variables.tf
Adds variables so the Atlantis ALB will log to a specified S3 bucket using a specified prefix. By default, logging is disabled to be backwards compatible.
> Add optional support for ALB logging

- outputs.tf
I want to trigger a `null_resource` to wait for the deployment to complete. Adding a `task_definition` output gives me something to trigger on other than `uuid()`
> Add Task Definition Output

- README.md
- main.tf
- variables.tf
This change is to allow a list of security group IDs to be added to the load balancer. This will enable externally created security groups to be passed through to the ALB module.
> Add capability to attach additional security groups to ALB

- main.tf
- terraform.tfvars.sample
- variables.tf
Add support for Bitbucket on prem by adding the ATLANTIS_BITBUCKET_BASE_URL environment variable to the container environment
> feat: add support for bitbucket stash base url

- main.tf
Added tags to cluster, task, ssm, role, and fmt
Specifically did not add it to ecs service as this mandates account level new arn format
More tags allows us to track resources down
None
terraform applied locally
> feat: Add tags to cluster, task, ssm, and role resources

- main.tf
Minor recreation of resources were required.
```
+ resource "aws_security_group_rule" "ingress_with_source_security_group_id" {
-/+ resource "aws_acm_certificate_validation" "this" {
```
> feat: Updated versions of VPC, SG, ACM modules

- README.md
- main.tf
- variables.tf
Example - Make Atlantis available on the root domain:
```
route53_zone_name = "atlantis.domain.com"
route53_record_name = ""
acm_certificate_domain_name = "atlantis.domain.com"
```
> feat: Allow custom Route53 record name (including empty)

- README.md
- main.tf
- variables.tf
This PR will allow this module to enforce authentication at the ALB, which is helpful when running Atlantis on the public internet. AWS Cognito is able to connect to your favorite identity provider using SAML.
> feat: Support ALB authentication using AWS Cognito

- README.md
Error in readme for cognito variables.
```
main.tf line 208, in resource "aws_lb_listener" "frontend_https":
208:           user_pool_domain                    = authenticate_cognito.value["user_pool_domain"]
|----------------
| authenticate_cognito.value is object with 3 attributes
The given key does not identify an element in this collection value.
```
> fix: cognito variables expect "user_pool_client_id" and "user_pool_domain"

- .pre-commit-config.yaml
- README.md
- main.tf
- variables.tf
remove the `aws_ssm_path` variable to get full proper ARN from SSM resources instead of building it manually
NONE
Run with the sample tfvars, added the changes and re-run to get no diffs (aside from regular ECS diff)
> feat: Refactor to use SSM ARNs directly from resources

- main.tf
Includes the `local.tags` in the `aws_ecs_service` resource.
For consistency, tags should be used across all the compatible resources created by the module. `aws_ecs_service` seems to be the only resource missing tags.
`no`
`applied locally`
> feat: Add tags to aws_ecs_service resource

- README.md
- main.tf
- variables.tf
Adds a new variable `var.tags_sgs_additional` to merge with the tags supplied on the security group resources that are open to the world. This is to add tags to those wide open security groups to pass our audits.
For auditing purposes
Closes https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/141
None
Locally
> feat: Additional tags to wide open security groups

- README.md
- main.tf
- variables.tf
See https://www.runatlantis.io/docs/access-credentials.html#generating-an-access-token
This is a new feature as of 0.14.0
This PR closes https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/147
It's much better to set this up as a github app instead of a github user as you have an easier interface for granular controls, app can be installed across an org, and app settings can control which repos have access to it.
None
1. Destroyed current atlantis
1. Recreated atlantis
1. Opened PR
1. Tested PR using a github app instead of a github user
> feat: Use atlantis bot instead of a github user

- README.md
- main.tf
- variables.tf
This expands the options by allowing users to add supplimentary container definitions in addition to the existing replacement of all container definitions.
The current limit is `var.ecs_task_cpu` is used for both the atlantis container definition and the task definition which means there's no room for any additional container definitions to use CPU. This is okay for me, as my sidecar exits 0 after writing files to the shared volume, but I may add a `var.ecs_container_cpu` which will default to `ecs_task_cpu` if it's not set, but will allow an author to expand the task CPU limits and the container limits independently. 
This allows me, in particular, to provide additional sidecars while still using the recommended container definitions. It primarily addresses #133 
This is a supplementary …
> feat: allow for extra_container_definitions

- README.md
- examples/github-complete/README.md
- examples/github-complete/main.tf
- examples/github-complete/terraform.tfvars.sample
- examples/github-complete/variables.tf
- main.tf
- variables.tf
Extra input variable to allow module users to optionally define extra principals that can assume the task role.
Apart from the main module code and documentation, the example is also updated to showcase how the new variable can be used.
At the moment, the only trusted entity to assume the task role is the absolute minimum `ecs-tasks.amazonaws.com`.
However sometimes it's convenient to allow adding more principals.
For example in order to allow easy SSM access into the Fargate task, `ssm.amazonaws.com` should be trusted too.
No breaking changes. Just adding an optional input variable.
From my project downstream, I have referenced this PR branch and applied my infrastructure. It works as expected.
> feat: allow adding more trusted principals to task role

- main.tf
This PR updates module dependencies to provide support for Terraform 0.14.
The versions of module dependencies that are used now set the `required_version` parameter as `< 0.14.0`, which means we cannot use the module with Terraform 0.14.
Does not break compatibility: the new versions are all backwards-compatible.
Tested with `terraform validate` on Terraform 0.14.
> fix: Update module dependencies for TF 0.14 support

- README.md
- examples/github-complete/main.tf
- main.tf
- variables.tf
Allow to set custom ECS Fargate platform version
currently, by default, ECS Fargate is using platform version 1.3.0
However, 1.4.0 introduce more features I would like Atlantis to use, including
- For tasks using platform version 1.4.0 or later that are launched on May 28, 2020 or later, the **ephemeral storage is encrypted with an AES-256 encryption algorithm** using an AWS Fargate-managed encryption key
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html
Nope, new variables are backward compatible and match existing defaults
planed and applied
> feat: support custom platform version

- README.md
- main.tf
- variables.tf
Added permissions boundary to iam role resource
Certain organisations require iam roles to be created with permissions boundary. This PR seeks to address those use cases
As the variable is optional, there will be no changes to existing resources
Tested by using in my own infrastructure
> feat: Add permissions boundary to ecs task iam role

- README.md
- main.tf
- variables.tf
Add `enable_ecs_managed_tags` and `propagate_tags` arguments to `aws_ecs_service`
More info here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service
Tagging tasks
None
Locally
> feat: Add enable_ecs_managed_tags and propagate_tags arguments to ecs_service

- README.md
- examples/github-complete/README.md
- examples/github-complete/versions.tf
- examples/github-repository-webhook/README.md
- examples/github-repository-webhook/versions.tf
- examples/gitlab-repository-webhook/README.md
- examples/gitlab-repository-webhook/versions.tf
- modules/github-repository-webhook/README.md
- modules/github-repository-webhook/versions.tf
- modules/gitlab-repository-webhook/README.md
- modules/gitlab-repository-webhook/versions.tf
- versions.tf
- update and correct versions used and required versions
- bump min version of terraform to 0.13 since it looks like GitLab does not support 0.12
- status checks are currently failing validation and this is intended to fix that
- Terraform 0.13 is min required version now
- ci-cd status checks
> chore: correct versions used and required versions

- README.md
- examples/github-complete/README.md
- examples/github-complete/main.tf
- main.tf
- modules/github-repository-webhook/README.md
- modules/gitlab-repository-webhook/README.md
- variables.tf
With the addition of #162 if a user includes extra container definitions and those definitions require CPU/Memory allocations the deployment will fail as the atlantis container definition takes the entire task cpu and memory allocation.
This allows a user to optionally fine tune the allocations of cpu and memory for the atlantis container definition. Most users won't require this feature, unless they're using `extra_container_definitions`.
fixes #168 
This does not break compatibility as by default the values are `null` and if `null` they will default to the `ecs_task_*` definitions, as it was before this change.
```hcl
module "datadog_fargate_container_definition" {
source  = "cloudposse/ecs-container-definition/aws"
version = "v0.41.0"
container_name  = "datadog-agent"
container_image = …
```
> feat: allow setting container memory & cpu from task memory & cpu

- README.md
- main.tf
- variables.tf
A data lookup for the latest task definition revision to be used in the
ECS service was enabled by default, which continually appeared in
plans/applies.
This is used when the task definition's updated by an external
deployment tool, so this is now disabled and requires enabling the
`external_task_definition_updates` variable so the default behaviour is
quiet.
A fix for #72 as an alternative to #124 which removed the functionality for external deployment tools.
I don't need the external tool support, but I am trying to make the default behaviour quieter and not show this update on every run.
Yes, for people using external deployment tools, they should set this new `external_task_definition_updates` variable to true. This feels like the exception as the default behaviour of the module is to …
> fix: Optionally lookup for the latest task definition

- .github/workflows/pre-commit.yml
- README.md
- examples/github-complete/README.md
- examples/github-repository-webhook/README.md
- examples/gitlab-repository-webhook/README.md
- modules/github-repository-webhook/README.md
- modules/gitlab-repository-webhook/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
> chore: update documentation and pin `terraform_docs` version to avoid future changes

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- LICENSE
- README.md
- examples/github-complete/main.tf
- Update CI/CD to use stable release v0.13 of `terraform-docs` to avoid breaking CI/CD checks based on [changes recently made to how `terraform-docs` distributes releases](https://github.com/terraform-docs/terraform-docs/pull/385)
- Add a discoverable Apache2.0 license that GitHub will recognize
- Yesterdays update to `terraform-docs` has yet again broken the CI/CD checks because we are trying to query the latest releases rather than a specific release artifact from downloads section
- No
- Documentation changes only, no source code changes
> chore: update CI/CD to use stable `terraform-docs` release artifact and discoverable Apache2.0 license

- README.md
- outputs.tf
Added alb/ecs/listeners outputs/
Added missing outputs, my motivation is deploy another containers in the same cluster and re-use alb
no
is outputs generate automatically, if yes please point me how to run?
> feat: Added outputs of ECS and ALB resources

- .github/workflows/pre-commit.yml
- README.md
- examples/github-complete/README.md
- examples/github-complete/main.tf
- examples/github-complete/outputs.tf
- examples/github-complete/terraform.tfvars.sample
- examples/github-complete/variables.tf
- examples/github-complete/versions.tf
- examples/github-repository-webhook/README.md
- examples/github-repository-webhook/main.tf
- examples/github-repository-webhook/outputs.tf
- examples/github-repository-webhook/terraform.tfvars.sample
- examples/github-repository-webhook/variables.tf
- examples/github-repository-webhook/versions.tf
- examples/gitlab-repository-webhook/README.md
- examples/gitlab-repository-webhook/outputs.tf
- examples/gitlab-repository-webhook/versions.tf
- main.tf
- modules/github-repository-webhook/README.md
- modules/github-repository-webhook/main.tf
- modules/github-repository-webhook/outputs.tf
- modules/github-repository-webhook/variables.tf
- modules/github-repository-webhook/versions.tf
- modules/gitlab-repository-webhook/README.md
- modules/gitlab-repository-webhook/outputs.tf
- modules/gitlab-repository-webhook/variables.tf
- modules/gitlab-repository-webhook/versions.tf
- outputs.tf
- variables.tf
- versions.tf
- add data source for using correct partition based on where Atlantis is provisioned for the default ECS task execution policy ARN
- update sub-modules to use latest versions; GitHub version need to be updated for deprecating changes
- bump min Terraform version to 0.13.1+ due to module and provider support
- replace `github_organization` with `github_owner` due to deprecation in the GitHub provider
- switch policy ARN attachment from `count` to `for_each` 
- correct `github-complete` example project so it works correctly again (trusted principals and trusted entities)
Closes #190
Closes #192
Closes #201
- Yes; support for Terraform v0.12.x is dropped, and GitHub provider min version supported raised to v4.8.x for deprecation of `github_organization`
- complete example updated and …
> BREAKING CHANGE: update internal modules to latest, replace `github_organization` with `github_owner`, bump Terraform version to >=0.13.1

- examples/github-complete/main.tf
- main.tf
per [Atlantis 0.17.1 release](https://github.com/runatlantis/atlantis/releases/tag/v0.17.1), the default image registry is ghcr.io. Thus updating the code to reflect that.
> feat: update default image to ghcr.io one

- examples/github-complete/outputs.tf
- examples/github-repository-webhook/outputs.tf
- examples/gitlab-repository-webhook/outputs.tf
- modules/github-repository-webhook/outputs.tf
- modules/gitlab-repository-webhook/outputs.tf
- outputs.tf
Add `sensitive = true` to all outputs where webhook secrets is used.
This will improve security.
no breaking changes
> feat: Add sensitive flag for webhook secret outputs

- README.md
We are using this with google oidc
Having google OIDC as an example makes sense for us: Especially since some may forget to configure their google consent screen to internal, that note could be worth mentioning.
Only readme example added
We run this example our selves in our envs.
> docs: Added google oidc example to readme

- README.md
- examples/github-complete/README.md
- examples/github-complete/versions.tf
- examples/github-repository-webhook/README.md
- examples/github-repository-webhook/versions.tf
- examples/gitlab-repository-webhook/README.md
- examples/gitlab-repository-webhook/versions.tf
- main.tf
- variables.tf
- versions.tf
Add the ability to use Fargate Ephemeral Storage
With multiple large plans being ran, it's possible to run the container out of disk space.  This enables the use of Fargate's ephemeral storage option to reduce that chance.
None
Been running it successfully for a couple months.
> feat: Add ability to use Fargate Ephemeral Storage

- .pre-commit-config.yaml
- .releaserc.json
- correct semantic-release message that is causing releases to fail
- Correct the release configuration template so that releases do not fail https://github.com/terraform-aws-modules/terraform-aws-atlantis/pull/237#issuecomment-973931742
- No
- N/A - no source code change
> fix: correct semantic-release message that is causing releases to fail

- .pre-commit-config.yaml
- CHANGELOG.md
- ensure pre-commit is using https for pulling hooks
- standardize with rest of repositories
- No
- N/A
> fix: ensure pre-commit is using latest version via HTTPS

- main.tf
Update health check path for Atlantis.
* https://github.com/runatlantis/atlantis/pull/144
Atlantis has the `/healthz` endpoint for health checks. This endpoint should be used for health checks from ALB. 
For example, if Atlantis BASIC authentication is enabled, this endpoint is the only path that does not require authentication.
* https://github.com/runatlantis/atlantis/pull/1896
No.
> fix: atlantis health check path

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/stale-actions.yaml
- .pre-commit-config.yaml
- .releaserc.json
- outputs.tf
- update release configs based on EKS findings
- add PR title check and stale issue workflows from EKS module
- current configurations do not respect conventional commit conventions; this fixes that
- No
- N/A
> chore: Update release configs based on EKS findings

- modules/github-repository-webhook/README.md
- modules/github-repository-webhook/main.tf
- modules/github-repository-webhook/variables.tf
Add base URL for use with GitHub Enterprise.
Currently, the only way to use the module with GItHub Enterprise is via injecting the provider configuration. However, in recent versions of Terraform, `terraform validate` will treat it as an error. Adding a variable solves this issue.
No known.
> feat: Add base URL for GitHub Enterprise

- main.tf
Typ fix in local alb_authentication_method
> chore: Fixed typo in alb_authentication_method

- examples/github-complete/README.md
- examples/github-complete/main.tf
- examples/github-complete/terraform.tfvars.sample
- examples/github-complete/variables.tf
The [GitHub Complete example](https://github.com/terraform-aws-modules/terraform-aws-atlantis/tree/master/examples/github-complete) is broken because of #253. This PR fixes it.
I spend few hour trying to provision the Atlantis to Fargate with no luck. Then I found #253 and realised what was the issue. With these fixes everything executed without errors. 
This PR touches only examples folder, so I don't think it will introduce any breaking change.
> fix: Fix the GitHub Complete example

- main.tf
When specifying a user for running the container, e.g. using the `100:1000` Atlantis user on the default image, the `aws_efs_access_point` is correctly configured with said `posix_user`, but the ownership of the root directory is left as the default `root:root`. This can result in different permission issues, one of which is described in https://github.com/runatlantis/atlantis/issues/2221. By specifying the `creation_info`, we ensure that the user provided as the executing posix user also owns the directory. If desired, this change can be put behind a feature variable.
The issue described in https://github.com/runatlantis/atlantis/issues/2221 is the primary motivation for this change.
No breaking changes as such, but this will force recreation of an existing aws_efs_access_point and thus …
> feat: Ensure EFS is owned by the posix_user to avoid permission issues

- README.md
- main.tf
- variables.tf
Add `var.task_execution_session_duration` for task execution role.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role
The default max_session_duration for iam roles of 1 hour is insufficient for long-running terraform applies. This leads to runs breaking and failing to persist their state in s3, and often requires painful manual cleanup.
None
> feat: Add `task_execution_session_duration` for task execution role

- README.md
Four resources plus provider config appears to be enough to bring management of the ALB OIDC resources into terraform
Pardon me for skipping the template. It's just a doc update.
> chore: Link to Google provider resource for OIDC config

- README.md
- outputs.tf
Output variable vpc_nat_public_ips  added 
Atlantis can use internal resources like hashicorp vault that requires whitelisting so it will be very convinient for a lot of users to integrate the module into whole iaac
Locally tested
> feat: Add output with public IP for whitelisting

- README.md
- main.tf
- variables.tf
1. Be able to import EFS file system created by the other terraform module
No
> feat: Add arguments in EFS file system

- .pre-commit-config.yaml
- README.md
- examples/github-complete/README.md
- examples/github-complete/main.tf
- main.tf
- variables.tf
Add `path` variable to main.tf for resource `aws_iam_role.ecs_task_execution` to allow for creating this role under more than the default path `/`
This resolves an issue for accounts that don't allow creation of roles under the default "/" path. Like permissions_boundary the path is needed if governance rules only allow IAM role creation under `/mycustomrole/path/`
```# module.atlantis.aws_iam_role.ecs_task_execution will be created
+ resource "aws_iam_role" "ecs_task_execution" {
+ arn                   = (known after apply)
+ assume_role_policy    = jsonencode(
{
+ Statement = [
+ {
+ Action    = "sts:AssumeRole"
+ Effect    = "Allow"
+ Principal = {
+ Service = [
+ "ssm.amazonaws.com",
+ "ecs-tasks.amazonaws.com",
]
}
+ Sid       = ""
},
]
+ Version   = "2012-10-17"
}
)
+ create_date …
```
> feat: Add path option to IAM roles created under this module

- README.md
- examples/github-complete/README.md
- examples/github-complete/main.tf
- examples/github-complete/outputs.tf
- examples/github-complete/terraform.tfvars.sample
- examples/github-complete/variables.tf
- examples/github-repository-webhook/README.md
- examples/github-repository-webhook/main.tf
- examples/github-repository-webhook/variables.tf
- main.tf
- variables.tf
Allow users to utilize the GitHub App instead of a personal access token to execute Atlantis.
Enable the use of a GitHub App with Atlantis. In this PR, four variables were added to the module and their dependencies: 
- `var.atlantis_github_app_key` 
- `var.atlantis_github_app_key_ssm_parameter_name`
- `var.atlantis_write_git_creds`
- `var.atlantis_github_app_id`
Note: It is not necessary to create a specific variable for the webhook secret in the GitHub App, the existing one can be used.
- fixes #271
ref:https://www.runatlantis.io/docs/access-credentials.html#generating-an-access-token (GitHub App section)
None
Initially, a github app was created and consequently a private key and a secret webhook were associated with 
it. Posteriorly, a test repo was used with the inputs …
> feat: Added support for GitHub app

- main.tf
Removes the unnecessary VPC-wide ingress rule for using Atlantis with EFS. I've confirmed that the [ingress rule from the Atlantis Security Group](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/main.tf#L404-L406) is sufficient. 
This should also resolve https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/252
None
> fix: Remove unneeded ingress for EFS traffic from the entire VPC

- README.md
- main.tf
Attempt to resolve https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/324. I believe this is due to the fact that the nfs submodule is trying to create a duplicate NFS ingress that conflicts with the one defined [here](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/master/main.tf#L403-L406). This PR used the base `security-group` module and relies on 
```hcl
ingress_with_source_security_group_id = [{
rule                     = "nfs-tcp",
source_security_group_id = module.atlantis_sg.security_group_id
}]
```
to configure the efs ingress rules. 
Resolves https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/324
This will cause a brief breakage for atlantis as it will replace security groups due to the need to switch modules. A …
> feat: Use base security-group module to remove duplicate EFS security group

- examples/gitlab-repository-webhook/README.md
- examples/gitlab-repository-webhook/versions.tf
- modules/gitlab-repository-webhook/README.md
- modules/gitlab-repository-webhook/versions.tf
This will hopefully fix the pre-commit issues popping up in https://github.com/terraform-aws-modules/terraform-aws-atlantis/pull/343
To fix broken pre-commits
None
> fix: Gitlab versioning errors with terraform 0.13

- main.tf
- Correct EFS mount 
- Replace the https listeners `authenticate_cognito` and `authenticate_oidc` with an overriding argument of `https_listener` where those values can be provided by users
- Resolves #367 
- Currently, when you deploy the module and values are not provided to one or both of `authenticate_cognito` or `authenticate_oidc` of the HTTPs listener, Terraform throws an error that a default action was not provided. This is because the argument keys are provide, but not values, and [the underlying ALB module](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/e3586dd0769e9aead190b980a041405f258fb1cd/main.tf#L80) is only checking to see if the key is present to determine if it should create the associated configuration. This must have been a late change on v9.0 that …
> fix: Correct EFS mount and correct listener authentication when value is not provided

- examples/github-separate/README.md
- examples/github-separate/main.tf
- main.tf
- Ensure conditional creation of EFS and entire module are functioning as intended
- I have updated the `github-separate/` example to remove EFS support since this use case is covered by `github-complete/`, and also added a disabled module definition to ensure that disabling the module creation works as intended. These changes demonstrated the issue in #369 plus a few other issues which have been corrected
- Resolves #369 
- No
- Validated with both examples
> fix: Ensure conditional creation of EFS and entire module are functioning as intended

- main.tf
- Correct security group egress rule lookup name - looks like a copy+paste typo causing ingress rules to be added to the egress rules
- Resolves #371 
- No
> fix: Correct security group egress rule lookup name

- main.tf
Following the upgrade to Terraform ALB module major version 9, it is essential to note that the target group arguments `backend_protocol` and `backend_port` now require adjustment. Going forward, these should be replaced with `protocol` and `port` respectively.
> fix: Correct ALB atlantis target group protocol and port arguments

- examples/github-separate/main.tf
- main.tf
In the definition of the local variable `atlantis_url`, currently attributes of `module.alb` are referenced within a `coalesce` function call. `coalesce` isn't short-circuiting, so even if `var.atlantis.fqdn` was provided, it won't be used in the case when an existing ALB is used: the reference to `module.alb.route53_records["A"]` will fail, and the error will be caught by the top-level `try`, leaving `atlantis_url` as `https://`.
In this change, the individual references to `module.alb` are wrapped in `try` calls, meaning that `var.atlantis.fqdn` will be respected if provided.
This change fixes this issue: https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/377
With this change, links in the "Checks" section of a Github pull request point to the correct URL.
This …
> fix: FQDN detection when using an existing ALB

- main.tf
Add `name = var.name` property to the EFS module. This value is added as a tag to the EFS file system by the EFS module.
- Fixes #386
> fix: Add 'Name' Tag to EFS File System

- README.md
- main.tf
- variables.tf
Make the ALB https listener default action configurable
This PR adds a new variable `alb_https_default_action` that allows configuring the default action for the ALB https listener.
In my scenario, I wanted the default action to be a blocking one (send a fixed response instead of forwarding to Atlantis target group).
The reason for it is that I'm adding a rule that grants access through OIDC Authentication, but for that to make sense I need to have a default rule that doesn't forward.
Currently, this default action is hardcoded so this PR adds a variable to allow overriding it.
No breaking change, the new variable defaults to the value that preserves current behaviour
> feat: Configurable default action https listener

- main.tf
The logic to name EFS was added, but it is tied to the main "name" variable for the module, and does not contain the logic to allow for uniques names when passing them in differently. 
Declaring a unique name in the EFS array did not allow for setting unique names. Default/unique name for the module was applied from the Atlantis module.
> feat: Add support for different name for EFS 

- .pre-commit-config.yaml
- examples/github-complete/README.md
- examples/github-complete/main.tf
- examples/github-complete/terraform.tfvars.sample
- examples/github-complete/variables.tf
- examples/github-separate/README.md
- examples/github-separate/main.tf
- examples/github-separate/terraform.tfvars.sample
- examples/github-separate/variables.tf
- Update examples to show inputs required for Atlantis vs the webhook
- Resolves #394
- Closes #395
- No, just updates the examples
> docs: Update examples to show inputs required for Atlantis vs the webhook

- .pre-commit-config.yaml
- main.tf
- Change default deployment percentages when using EFA to allow updates to succeed
- Resolves #383
- No; this changes the default value (when one is not provided by users) when `enable_efa = true` which according to #383, does not work as intended today
> fix: Change default deployment percentages when using EFS to allow updates to succeed

- .github/workflows/pr-title.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- README.md
- examples/github-complete/README.md
- examples/github-separate/README.md
- modules/github-repository-webhook/README.md
- modules/gitlab-repository-webhook/README.md
- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No
> fix: Update CI workflow versions to latest
